package handler

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"

	"github.com/raworiginal/goNotes/internal/config"
	repo "github.com/raworiginal/goNotes/internal/repository"
	"github.com/raworiginal/goNotes/internal/token"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/github"
	"golang.org/x/oauth2/google"
)

type OAuthHandler struct {
	store      *repo.Store
	cfg        *config.Config
	githubConf *oauth2.Config
	googleConf *oauth2.Config
}

func NewOAuthHandler(store *repo.Store, cfg *config.Config) *OAuthHandler {
	return &OAuthHandler{
		store: store,
		cfg:   cfg,
		githubConf: &oauth2.Config{
			ClientID:     cfg.GitHubClientID,
			ClientSecret: cfg.GitHubClientSecret,
			RedirectURL:  cfg.BaseURL + "/auth/github/callback",
			Scopes:       []string{"user:email"},
			Endpoint:     github.Endpoint,
		},
		googleConf: &oauth2.Config{
			ClientID:     cfg.GoogleClientID,
			ClientSecret: cfg.GoogleClientSecret,
			RedirectURL:  cfg.BaseURL + "/auth/google/callback",
			Scopes:       []string{"openid", "email", "profile"},
			Endpoint:     google.Endpoint,
		},
	}
}

// generateState creates a random value and signs it with HMAC so we can verify it on callback.
func (h *OAuthHandler) generateState() (string, error) {
	raw := make([]byte, 16)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	nonce := hex.EncodeToString(raw)
	mac := hmac.New(sha256.New, []byte(h.cfg.OAuthStateSecret))
	mac.Write([]byte(nonce))
	sig := hex.EncodeToString(mac.Sum(nil))
	return nonce + "." + sig, nil
}

// verifyState checks that the state param was generated by this server.
func (h *OAuthHandler) verifyState(state string) bool {
	if len(state) < 34 {
		return false
	}
	dotIdx := len(state) - 65 // nonce(32) + "." + sig(64)
	if dotIdx < 0 || state[dotIdx] != '.' {
		return false
	}
	nonce := state[:dotIdx]
	sig := state[dotIdx+1:]
	mac := hmac.New(sha256.New, []byte(h.cfg.OAuthStateSecret))
	mac.Write([]byte(nonce))
	expected := hex.EncodeToString(mac.Sum(nil))
	return hmac.Equal([]byte(sig), []byte(expected))
}

func (h *OAuthHandler) redirectError(w http.ResponseWriter, r *http.Request, reason string) {
	http.Redirect(w, r, h.cfg.FrontendURL+"#error="+url.QueryEscape(reason), http.StatusTemporaryRedirect)
}

// GitHubLogin redirects the browser to GitHub's OAuth authorization page.
func (h *OAuthHandler) GitHubLogin(w http.ResponseWriter, r *http.Request) {
	state, err := h.generateState()
	if err != nil {
		jsonError(w, "internal server error", http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, h.githubConf.AuthCodeURL(state), http.StatusTemporaryRedirect)
}

// GoogleLogin redirects the browser to Google's OAuth authorization page.
func (h *OAuthHandler) GoogleLogin(w http.ResponseWriter, r *http.Request) {
	state, err := h.generateState()
	if err != nil {
		jsonError(w, "internal server error", http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, h.googleConf.AuthCodeURL(state), http.StatusTemporaryRedirect)
}

// GitHubCallback handles the redirect back from GitHub.
func (h *OAuthHandler) GitHubCallback(w http.ResponseWriter, r *http.Request) {
	if !h.verifyState(r.URL.Query().Get("state")) {
		h.redirectError(w, r, "invalid_state")
		return
	}

	oauthToken, err := h.githubConf.Exchange(context.Background(), r.URL.Query().Get("code"))
	if err != nil {
		h.redirectError(w, r, "token_exchange_failed")
		return
	}

	providerUID, email, err := fetchGitHubUser(oauthToken.AccessToken)
	if err != nil {
		h.redirectError(w, r, "fetch_user_failed")
		return
	}

	h.handleOAuthCallback(w, r, "github", providerUID, email)
}

// GoogleCallback handles the redirect back from Google.
func (h *OAuthHandler) GoogleCallback(w http.ResponseWriter, r *http.Request) {
	if !h.verifyState(r.URL.Query().Get("state")) {
		h.redirectError(w, r, "invalid_state")
		return
	}

	oauthToken, err := h.googleConf.Exchange(context.Background(), r.URL.Query().Get("code"))
	if err != nil {
		h.redirectError(w, r, "token_exchange_failed")
		return
	}

	providerUID, email, err := fetchGoogleUser(oauthToken.AccessToken)
	if err != nil {
		h.redirectError(w, r, "fetch_user_failed")
		return
	}

	h.handleOAuthCallback(w, r, "google", providerUID, email)
}

// handleOAuthCallback contains the find-or-create user logic shared by all providers.
func (h *OAuthHandler) handleOAuthCallback(w http.ResponseWriter, r *http.Request, provider, providerUID, email string) {
	user, err := h.store.OAuth.FindUserByProvider(provider, providerUID)
	if err != nil && err != repo.ErrNotFound {
		h.redirectError(w, r, "internal_error")
		return
	}

	if err == repo.ErrNotFound {
		_, emailErr := h.store.Users.FindUserByEmail(email)
		if emailErr == nil {
			h.redirectError(w, r, "account_exists")
			return
		}
		if emailErr != repo.ErrNotFound {
			h.redirectError(w, r, "internal_error")
			return
		}
		username := provider + "_" + providerUID
		user, err = h.store.OAuth.CreateOAuthUser(username, &email, provider, providerUID)
		if err != nil {
			h.redirectError(w, r, "internal_error")
			return
		}
	}

	code := rand.Text()
	if err := h.store.OAuth.CreateOAuthCode(user.ID, code, time.Now().Add(2*time.Minute)); err != nil {
		h.redirectError(w, r, "internal_error")
		return
	}
	http.Redirect(w, r, h.cfg.FrontendURL+"#code="+code, http.StatusTemporaryRedirect)
}

type ExchangeRequest struct {
	Code string `json:"code"`
}

// Exchange trades a one-time OAuth code for a JWT access token + refresh token.
func (h *OAuthHandler) Exchange(w http.ResponseWriter, r *http.Request) {
	var req ExchangeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.Code == "" {
		jsonError(w, "invalid request", http.StatusBadRequest)
		return
	}

	user, err := h.store.OAuth.ExchangeOAuthCode(req.Code)
	if err != nil {
		jsonError(w, "invalid or expired code", http.StatusUnauthorized)
		return
	}

	accessToken, err := token.SignAccessToken(user.ID, h.cfg.JWTSecret, h.cfg.AccessTokenTTL)
	if err != nil {
		jsonError(w, "internal server error", http.StatusInternalServerError)
		return
	}

	refreshToken, err := token.GenerateRefreshToken()
	if err != nil {
		jsonError(w, "internal server error", http.StatusInternalServerError)
		return
	}

	refreshExpiry := time.Now().Add(h.cfg.RefreshTokenTTL)
	if err := h.store.Tokens.CreateToken(user.ID, refreshToken, refreshExpiry); err != nil {
		jsonError(w, "internal server error", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(LoginResponse{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
	})
}

// fetchGitHubUser calls the GitHub API and returns the user's providerUID and primary email.
func fetchGitHubUser(accessToken string) (providerUID string, email string, err error) {
	req, _ := http.NewRequest("GET", "https://api.github.com/user", nil)
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer resp.Body.Close()

	var profile struct {
		ID    int64  `json:"id"`
		Login string `json:"login"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&profile); err != nil {
		return "", "", err
	}

	// Fetch primary verified email
	emailReq, _ := http.NewRequest("GET", "https://api.github.com/user/emails", nil)
	emailReq.Header.Set("Authorization", "Bearer "+accessToken)
	emailReq.Header.Set("Accept", "application/vnd.github+json")

	emailResp, err := http.DefaultClient.Do(emailReq)
	if err != nil {
		return "", "", err
	}
	defer emailResp.Body.Close()

	body, _ := io.ReadAll(emailResp.Body)
	var emails []struct {
		Email    string `json:"email"`
		Primary  bool   `json:"primary"`
		Verified bool   `json:"verified"`
	}
	if err := json.Unmarshal(body, &emails); err != nil {
		return "", "", err
	}

	for _, e := range emails {
		if e.Primary && e.Verified {
			return fmt.Sprintf("%d", profile.ID), e.Email, nil
		}
	}
	return "", "", fmt.Errorf("no verified primary email found")
}

// fetchGoogleUser calls the Google userinfo API and returns the user's providerUID and email.
func fetchGoogleUser(accessToken string) (providerUID string, email string, err error) {
	req, _ := http.NewRequest("GET", "https://www.googleapis.com/oauth2/v2/userinfo", nil)
	req.Header.Set("Authorization", "Bearer "+accessToken)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer resp.Body.Close()

	var profile struct {
		ID            string `json:"id"`
		Email         string `json:"email"`
		VerifiedEmail bool   `json:"verified_email"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&profile); err != nil {
		return "", "", err
	}

	if !profile.VerifiedEmail {
		return "", "", fmt.Errorf("google email not verified")
	}
	return profile.ID, profile.Email, nil
}
